services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: onlinegologistics_backend
    restart: always
    ports:
      - "5003:5003"
    env_file:
      - ./backend/.env
    volumes:
      - ./wa-auth:/app/wa-auth
    networks:
      - app-network

networks:
  app-network:
    driver: bridge